-- VHDL module instantiation generated by SCUBA ispLever_v72_SP2_Build (23)
-- Module  Version: 5.2
-- Sat Dec 26 00:12:59 2009

-- parameterized module component declaration
component fifo_2048x8
    port (Data: in  std_logic_vector(7 downto 0); WrClock: in  std_logic; 
        RdClock: in  std_logic; WrEn: in  std_logic; RdEn: in  std_logic; 
        Reset: in  std_logic; RPReset: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0); Empty: out  std_logic; 
        Full: out  std_logic);
end component;

-- parameterized module component instance
__ : fifo_2048x8
    port map (Data(7 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(7 downto 0)=>__, Empty=>__, 
        Full=>__);
