-- VHDL module instantiation generated by SCUBA ispLever_v8.0_PROD_Build (41)
-- Module  Version: 5.4
-- Mon Jul 26 21:40:04 2010

-- parameterized module component declaration
component fifo_64kx9
    port (Data: in  std_logic_vector(8 downto 0); WrClock: in  std_logic; 
        RdClock: in  std_logic; WrEn: in  std_logic; RdEn: in  std_logic; 
        Reset: in  std_logic; RPReset: in  std_logic; 
        Q: out  std_logic_vector(8 downto 0); Empty: out  std_logic; 
        Full: out  std_logic);
end component;

-- parameterized module component instance
__ : fifo_64kx9
    port map (Data(8 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(8 downto 0)=>__, Empty=>__, 
        Full=>__);
